### PR TITLE
First go at tabledemo 

### PR DESCRIPTION
**Pull request by wxmerkt**
First go to run on robot

### CODE REVIEW

**Comment by patmarion** [comment]
we should skype sometime to talk about these task demos, i'd love to discuss ideas for future improvements so that these can be easier to develop, maintain, and share between robots and labs.

**Comment by wxmerkt** [comment]
Yes, this is quick and dirty to get something going and will be cleaned up tonight or tomorrow. That's also why it's against our own branch while setting up the robot and not the master

**Comment by patmarion** [comment]
oh, i didn't even notice which branch this was being merged to!

I think it's great to see the table demo being used for Val, nice job!  Please don't hesitate to share some video or screenshots, even if it's only partially working, id even just like to see how the perception segmentation is working out.

I don't just mean improvements to the table demo, but improvements to the whole task planning and execution design.  I'd like to support planning all the steps into the future and playback of all steps (kinematic playback) with affordance interactions, like in this video:

https://www.youtube.com/watch?v=U5d0nEE_Afw

we lost support for doing that type of playback some time ago.

**Comment by wxmerkt** [comment]
I believe some of that functionality has been added back by myself during the summer and was working in tabledemo before the new FPP changes were merged in ~October. Need to get it running again soon, so will report back

**Comment by mauricefallon** [comment]
> we should skype sometime to talk about these task demos, i'd love to discuss ideas for future 
> improvements so that these can be easier to develop, maintain, and share between robots and labs.

certainly, lets talk next week perhaps.

**Pull request merged**
